(source gnu)
(source melpa)

(depends-on "pallet")
(depends-on "popup")
(depends-on "auto-complete")
(depends-on "enh-ruby-mode")
(depends-on "smartparens")
(depends-on "projectile")
(depends-on "swiper")
(depends-on "rainbow-mode")
(depends-on "robe")
(depends-on "highlight-indentation")
(depends-on "visible-mark")
(depends-on "web-mode")
(depends-on "yaml-mode")
(depends-on "dash-at-point")
(depends-on "seeing-is-believing")
(depends-on "plan9-theme")
(depends-on "exec-path-from-shell")
(depends-on "auto-indent-mode")
(depends-on "chruby")

(depends-on "ledger-mode")
