(source melpa)

(depends-on "pallet")
(depends-on "auto-complete")
(depends-on "enh-ruby-mode")
(depends-on "smartparens")
(depends-on "projectile")
(depends-on "swiper")
(depends-on "rainbow-mode")
(depends-on "robe")
(depends-on "highlight-indentation")
(depends-on "visible-mark")
(depends-on "web-mode")
(depends-on "yaml-mode")